# Linear Model

# Quiz 1

## Requirement:
1. `def linear_regression_1d`
   * Input: 
   * Return: (m,c) 
     * m: the slope of the line of least squares fit
     * c: the intercept of the line  of least squares fit


In [26]:
import numpy as np

def linear_regression_1d(data):
    n = len(data) 
    X = [] ; Y = []
    for i in range(n):
        X.append( np.array(data[i][0]))
        Y.append( np.array(data[i][1]))
    m = (n * np.dot(X,Y) - sum(X)*sum(Y)) / (n*np.dot(X,X) - sum(X)*sum(X))
    c = (sum(Y) - m * sum(X)) / n
    return m,c
    

data = [(1, 4), (2, 7), (3, 10)]
length = linear_regression_1d(data)
print(length)

(3.0, 1.0)


In [1]:
import numpy as np
def linear_regression_1d2(data):
    n = len(data) 
    X,Y = zip(*data)
    sum_x = sum(X); sum_y = sum(Y)
    sum_xx = sum(i**2 for i in X);
    sum_xy = sum(X[i] * Y[i] for i in range(n))

    m = (n * sum_xy - sum_x* sum_y) / (n * sum_xx - sum_x**2)
    c = (sum_y - m * sum_x) / n
    return m,c

### Test Case
* Expect result:    
3.0 1.0    
13.0

In [2]:
data = [(1, 4), (2, 7), (3, 10)]
m, c = linear_regression_1d2(data)
print(m, c)
print(4 * m + c)

3.0 1.0
13.0


# Quiz 2

## Requirements: 
1. `def linear_regression(xs,ys)`
   * Input: 2 np.array
   * xs: matrix (nxd)
   * ys: one-dimensional array (n)


In [27]:
def linear_regression(xs,ys):
    
    A = np.c_[np.ones((xs.shape[0],1)),xs]
    Inv_xs = np.linalg.inv(A.T @ A)
    theta = Inv_xs @ A.T @ ys
    return theta

xs = np.arange(5).reshape((-1, 1))
# print(xs)
ys = np.arange(1, 11, 2)
print(linear_regression(xs, ys))


[1. 2.]


## Test Case 1
* Expect   
`[1. 2.]`

In [4]:
import numpy as np

xs = np.arange(5).reshape((-1, 1))
print(xs)
ys = np.arange(1, 11, 2)
print(ys)
# print(linear_regression(xs, ys))

[[0]
 [1]
 [2]
 [3]
 [4]]
[1 3 5 7 9]


## Test Case 2
* Expect   
`[-1. 2. 1.]`

In [28]:
import numpy as np

xs = np.array([[1, 2, 3, 4],
               [6, 2, 9, 1]]).T
ys = np.array([7, 5, 14, 8]).T
print(linear_regression(xs, ys))

[-1.  2.  1.]


# Quiz3 - Guassian Distribution